use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ExpertField {
    pub path: &'static str,
    pub label: &'static str,
    pub unit: &'static str,
    pub minimum: Option<i64>,
    pub maximum: Option<i64>,
    pub choices: &'static [&'static str],
    pub impact: &'static str,
}
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ExpertPanel {
    pub id: &'static str,
    pub label: &'static str,
    pub experimental: bool,
    pub fields: Vec<ExpertField>,
}

/// Tauri/React 专家面板的唯一字段描述源。前端展示继承值/有效值时同时调用
/// `resolve_without_encoding`，不复制后端范围、单位或枚举默认。
///
/// 覆盖 V2 稳定公开字段（`QuantizationTuning`/`ChromaTuning`/`PerceptualTuning`/
/// `TemporalTuning`/`RateControlV2`/`FirstFrameTuning`/`PerformanceTuning`）与
/// 实验字段；`base.revision`、`apiVersion`、`allowIgnored` 等内部/元字段不暴露。
pub fn expert_panel_schema() -> Vec<ExpertPanel> {
    vec![
        panel(
            "basic",
            "质量与码率",
            false,
            vec![
                field(
                    "base.qualityX100",
                    "质量",
                    "Q×100",
                    100,
                    10000,
                    &[],
                    "增大通常提高质量和体积",
                ),
                field(
                    "rate.mode",
                    "码率模式",
                    "",
                    0,
                    0,
                    &[
                        "constant-quality",
                        "target-bytes",
                        "target-bpp",
                        "constrained-quality",
                    ],
                    "质量优先或大小约束",
                ),
                field(
                    "rate.targetBytes",
                    "目标字节",
                    "bytes",
                    1,
                    i64::MAX,
                    &[],
                    "限制完整 CRF 目标大小",
                ),
                field(
                    "rate.minQualityX100",
                    "质量下限",
                    "Q×100",
                    100,
                    10000,
                    &[],
                    "码率控制不得突破的最低质量",
                ),
                field(
                    "rate.maxBytes",
                    "字节上限",
                    "bytes",
                    1,
                    i64::MAX,
                    &[],
                    "硬上限，无法满足时返回错误",
                ),
                field(
                    "performance.effort",
                    "编码努力",
                    "level",
                    0,
                    10,
                    &[],
                    "增大搜索范围和耗时",
                ),
            ],
        ),
        panel(
            "firstFrame",
            "首帧",
            false,
            vec![
                field(
                    "firstFrame.mode",
                    "首帧模式",
                    "",
                    0,
                    0,
                    &["match-sequence", "lossless", "quality-offset", "explicit"],
                    "控制首帧质量与码率分配",
                ),
                field(
                    "firstFrame.qualityOffsetX100",
                    "质量偏移",
                    "Q×100",
                    -2000,
                    2000,
                    &[],
                    "正值提高首帧质量",
                ),
                field(
                    "firstFrame.qualityX100",
                    "首帧质量",
                    "Q×100",
                    100,
                    10000,
                    &[],
                    "仅 explicit 模式生效",
                ),
                field(
                    "firstFrame.maxBytes",
                    "首帧字节上限",
                    "bytes",
                    1,
                    i64::MAX,
                    &[],
                    "单独约束 frame0 载荷",
                ),
            ],
        ),
        panel(
            "quant",
            "量化",
            false,
            vec![
                field(
                    "quant.deadzoneLumaX256",
                    "亮度死区",
                    "/256",
                    -128,
                    256,
                    &[],
                    "增大稀疏化强度",
                ),
                field(
                    "quant.chromaScaleX1000",
                    "色度量化倍率",
                    "×1000",
                    500,
                    4000,
                    &[],
                    "增大降低色度码率",
                ),
                field(
                    "quant.deadzoneChromaX256",
                    "色度死区",
                    "/256",
                    -128,
                    256,
                    &[],
                    "增大稀疏化强度",
                ),
                field(
                    "quant.matrix",
                    "量化矩阵",
                    "",
                    0,
                    0,
                    &["auto", "flat", "perceptual", "edge-preserving"],
                    "感知矩阵释放高频色度码率",
                ),
                field(
                    "quant.rdoq",
                    "RDOQ 等级",
                    "",
                    0,
                    0,
                    &["auto", "off", "fast", "full"],
                    "Trellis 量化努力等级",
                ),
            ],
        ),
        panel(
            "chroma",
            "色度采样",
            false,
            vec![
                field(
                    "chroma.sampling",
                    "色度采样",
                    "",
                    0,
                    0,
                    &["auto", "444", "422", "420"],
                    "420 显著降低色度码率",
                ),
                field(
                    "chroma.downsampleFilter",
                    "下采样滤波",
                    "",
                    0,
                    0,
                    &["auto", "box", "bilinear", "six-tap"],
                    "下采样抗混叠滤波",
                ),
                field(
                    "chroma.upsampleFilter",
                    "上采样滤波",
                    "",
                    0,
                    0,
                    &["auto", "bilinear", "four-tap", "six-tap"],
                    "解码重建滤波",
                ),
                field(
                    "chroma.siting",
                    "色度位置",
                    "",
                    0,
                    0,
                    &["auto", "centered", "cosited"],
                    "色度样本位置",
                ),
                field(
                    "chroma.edgeProtectionX100",
                    "色度边缘保护",
                    "×100",
                    0,
                    200,
                    &[],
                    "防饱和色边界渗色",
                ),
            ],
        ),
        panel(
            "perceptual",
            "感知保护",
            false,
            vec![
                field(
                    "perceptual.flatAreaProtectionX100",
                    "平坦区保护",
                    "×100",
                    0,
                    200,
                    &[],
                    "增大降低渐变 banding 风险",
                ),
                field(
                    "perceptual.edgeProtectionX100",
                    "边缘保护",
                    "×100",
                    0,
                    200,
                    &[],
                    "增大保护文字和线稿",
                ),
                field(
                    "perceptual.activityMaskingX100",
                    "活动掩蔽",
                    "×100",
                    0,
                    200,
                    &[],
                    "增大允许纹理区更强量化",
                ),
                field(
                    "perceptual.noiseMode",
                    "噪声模式",
                    "",
                    0,
                    0,
                    &["off", "auto", "manual"],
                    "有损源噪声处理策略",
                ),
                field(
                    "perceptual.noiseTauX100",
                    "噪声阈值",
                    "×100",
                    50,
                    400,
                    &[],
                    "仅 manual 模式生效",
                ),
            ],
        ),
        panel(
            "temporal",
            "时间预测",
            false,
            vec![
                field(
                    "temporal.referenceMode",
                    "参考策略",
                    "",
                    0,
                    0,
                    &["auto", "golden", "previous", "hybrid"],
                    "Hybrid 逐帧竞争重建参考",
                ),
                field(
                    "temporal.changeMask",
                    "变化掩码",
                    "",
                    0,
                    0,
                    &["off", "auto", "on"],
                    "静止 tile 零载荷",
                ),
                field(
                    "temporal.motionMode",
                    "位移补偿",
                    "",
                    0,
                    0,
                    &["off", "auto", "integer"],
                    "轻量整数位移搜索",
                ),
                field(
                    "temporal.motionRange",
                    "位移范围",
                    "pixels",
                    0,
                    32,
                    &[],
                    "增大整数位移搜索范围",
                ),
                field(
                    "temporal.sceneCut",
                    "场景切换",
                    "",
                    0,
                    0,
                    &["off", "auto", "manual"],
                    "切换时回退 golden 锚点",
                ),
                field(
                    "temporal.sceneCutThresholdX1000",
                    "场景阈值",
                    "×1000",
                    0,
                    1000,
                    &[],
                    "仅 manual 模式生效",
                ),
                field(
                    "temporal.anchorInterval",
                    "锚点间隔",
                    "frames",
                    0,
                    65535,
                    &[],
                    "缩短间隔改善随机访问",
                ),
                field(
                    "temporal.anchorQualityOffsetX100",
                    "锚点质量偏移",
                    "Q×100",
                    -2000,
                    2000,
                    &[],
                    "正值提高锚点质量",
                ),
            ],
        ),
        panel(
            "experimental",
            "实验工具",
            true,
            vec![
                field(
                    "experimental.palette",
                    "局部调色板",
                    "",
                    0,
                    0,
                    &["auto", "off", "on"],
                    "低色数 UI/赛璐璐可能受益",
                ),
                field(
                    "experimental.transformSkip",
                    "变换跳过",
                    "",
                    0,
                    0,
                    &["auto", "off", "on"],
                    "线稿/文字保护与消融",
                ),
                field(
                    "experimental.tileSize",
                    "Tile 尺寸",
                    "px",
                    0,
                    65535,
                    &[],
                    "首帧固定 tile 探针",
                ),
                field(
                    "experimental.rdoCandidateLimit",
                    "候选上限",
                    "count",
                    0,
                    65535,
                    &[],
                    "非零值可能改变率失真结果",
                ),
            ],
        ),
        panel(
            "performance",
            "性能",
            false,
            vec![
                field(
                    "performance.threads",
                    "线程数",
                    "count",
                    0,
                    65535,
                    &[],
                    "0 = 自动",
                ),
                field(
                    "performance.deterministic",
                    "确定性",
                    "",
                    0,
                    0,
                    &["false", "true"],
                    "相同输入产生相同码流",
                ),
                field(
                    "performance.fastFail",
                    "Fast-Fail",
                    "",
                    0,
                    0,
                    &["off", "auto", "on"],
                    "仅启用数学上安全的剪枝",
                ),
            ],
        ),
    ]
}

fn panel(
    id: &'static str,
    label: &'static str,
    experimental: bool,
    fields: Vec<ExpertField>,
) -> ExpertPanel {
    ExpertPanel {
        id,
        label,
        experimental,
        fields,
    }
}
fn field(
    path: &'static str,
    label: &'static str,
    unit: &'static str,
    minimum: i64,
    maximum: i64,
    choices: &'static [&'static str],
    impact: &'static str,
) -> ExpertField {
    ExpertField {
        path,
        label,
        unit,
        minimum: choices.is_empty().then_some(minimum),
        maximum: choices.is_empty().then_some(maximum),
        choices,
        impact,
    }
}
